### ISSUE TITLE
Passing any sample attribute as argument to a pipeline CLI

### ISSUE THREAD

**Issue by afrendeiro** [epigen/looper#16]
Assume I want to make a pipeline that does not rely on Pypiper but uses looper.

How do I get the `parent_dir` or `sample_root` argument to a passed to my pipeline without pypiper arguments?

What I can think of is something like the following in the pipeline_interface.yaml:

```yaml
new_pipe.py:
  arguments:
    "-n": sample_name
    "-p": prj.paths.parent_dir
  looper_args: False
```
or stuff like
```yaml
    "-p": paths.sample_root
```
but this doesn't work. 

How would one do this?

**Comment by nsheff** [comment]
Maybe it can't -- since the output dir is not a sample attribute, but a project attribute; looper only knows how to pass sample attributes to pipelines...

Now, if parent_dir is in fact a sample attribute, which it may be, then you can using just what you're doing:

```yaml
new_pipe.py:
  arguments:
    "-n": sample_name
    "-p": parent_dir  # (whatever the attribute name is here)
  looper_args: False
```

Is it that you're just using the wrong string? isn't it: `prj.paths.output_dir`  (not `parent_dir`). Can you nest down like that? It might work...
