### ISSUE TITLE
looper is not populating flag-like arguments from pipeline interface

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#183]
How can I pass a flag-like (parameter-less) argument in pipeline interface?
 If I try to specify like this:
```
pipelines:
  fastq-dump:
    name: fastq-dump
    path: /usr/bin/fastq-dump
    arguments: 
      "--split-3": null
```

it does not work. If I try to specify like this:
```

pipelines:
  fastq-dump:
    name: fastq-dump
    path: "/usr/bin/fastq-dump --split-3"
    arguments: 
      "-O": sra_folder
      "": data_source
```

It says: `Missing pipeline script: '/usr/bin/fastq-dump --split-3'` and fails

I think both of these should work.
